language: scala
sudo: false
jdk:
- oraclejdk8

scala:
- 2.11.12
- 2.12.7

before_install:
- export LD_LIBRARY_PATH=$HOME/lib
- "./.travis/setup.sh"

script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverageTest

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
  - "$HOME/.sbt/launchers/"
  - "$HOME/.zinc"
  - "$HOME/.coursier"
  - "$HOME/lib"

after_success:
# work around https://github.com/codecov/codecov-bash/issues/133
- curl -s https://codecov.io/bash > .codecov
- sed -i -e 's/TRAVIS_.*_VERSION/^TRAVIS_.*_VERSION=/' .codecov
- chmod +x .codecov
- |
  if [[ $TRAVIS_SCALA_VERSION == 2.12.7 ]]; then ./.codecov; fi

before_cache:
# Tricks to avoid unnecessary cache updates
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
