language: scala
sudo: false
jdk:
- oraclejdk8

scala:
- 2.11.12
- 2.12.7

before_install:
- export LD_LIBRARY_PATH=$HOME/lib
- "./.travis/setup.sh"

script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverageTest

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
  - "$HOME/.sbt/launchers/"
  - "$HOME/.zinc"
  - "$HOME/.coursier"
  - "$HOME/lib"

after_success:
- if [ "$TRAVIS_SCALA_VERSION" = "2.12.7" ]; then bash <(curl -s https://codecov.io/bash); fi

before_cache:
# Tricks to avoid unnecessary cache updates
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
